### PR TITLE
resolves #798 : Application features not working properly

### LINKED ISSUE #798: Application features not working properly
Cache invalidation and connector feature toggle

### PR DESCRIPTION
**Pull request by delphes99**

### CODE REVIEW

File: bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt [hunk 1]
```diff
@@ -101,25 +63,52 @@ internal object FeatureMongoDAO : FeatureDAO {
...
+            default.also {
+                addFeature(botId, namespace, default, category, name, null, null, null)
             }
+        } else {
+            val feature = (connectorFeature ?: globalFeature)!!
+            isEnabled(feature)
+        }
+    }
+
+    private fun isEnabled(feature: Feature): Boolean {
```
Comment (gsoumier) [inline bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt]: Why not in feature object ?

File: bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt [hunk 2]
```diff
@@ -101,25 +63,52 @@ internal object FeatureMongoDAO : FeatureDAO {
...
+        val now = ZonedDateTime.now(internalDefaultZoneId)
+        return when {
+            feature.startDate != null && feature.endDate == null -> feature.enabled && now.isAfter(feature.startDate)
+            feature.startDate != null && feature.endDate != null -> feature.enabled && now.isAfter(feature.startDate)
+                    && now.isBefore(feature.endDate)
+            else -> feature.enabled
+        }
+    }
+
+    private fun getValues(id: String, idWithoutApplicationId: String): Pair<Feature?, Feature?> {
```
Comment (gsoumier) [inline bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt]: Simple object instead of Pair<Feature, Feature> can have methods for :
- connectorFeature == null && globalFeature == null
- (connectorFeature ?: globalFeature)!!

File: bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt [hunk 3]
```diff
@@ -101,25 +63,52 @@ internal object FeatureMongoDAO : FeatureDAO {
...
+        val cacheForId = cache.stateOf(id)
+        val cacheForIdWithoutApplicationId = cache.stateOf(idWithoutApplicationId)
+        val pair = if (cacheForId == null && cacheForIdWithoutApplicationId == null) {
+            cacheAllConnectorFeatureWithId(idWithoutApplicationId)
```
Comment (gsoumier) [inline bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt]: Feature may never been added to cache if 
- feature is in admin / database without applicationId
- isEnable is called 
- add feature in admin for specific applicationId with different enable state
- isEnable called again

Comment (gsoumier) [reply bot/storage-mongo/src/main/kotlin/FeatureMongoDAO.kt]: EDIT : it works because of (thanks to invalidateListener in MongoFeatureCache) but it won't in other implementation : break Liskov substitution principle ?
